package com.project.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CusNoteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCusNoteAllPropertiesEquals(CusNote expected, CusNote actual) {
        assertCusNoteAutoGeneratedPropertiesEquals(expected, actual);
        assertCusNoteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCusNoteAllUpdatablePropertiesEquals(CusNote expected, CusNote actual) {
        assertCusNoteUpdatableFieldsEquals(expected, actual);
        assertCusNoteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCusNoteAutoGeneratedPropertiesEquals(CusNote expected, CusNote actual) {
        assertThat(expected)
            .as("Verify CusNote auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCusNoteUpdatableFieldsEquals(CusNote expected, CusNote actual) {
        assertThat(expected)
            .as("Verify CusNote relevant properties")
            .satisfies(e -> assertThat(e.getCreateBy()).as("check createBy").isEqualTo(actual.getCreateBy()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(e -> assertThat(e.getCreateDate()).as("check createDate").isEqualTo(actual.getCreateDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCusNoteUpdatableRelationshipsEquals(CusNote expected, CusNote actual) {
        assertThat(expected)
            .as("Verify CusNote relationships")
            .satisfies(e -> assertThat(e.getCustomer()).as("check customer").isEqualTo(actual.getCustomer()));
    }
}
