package com.project.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SourceOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceOrderAllPropertiesEquals(SourceOrder expected, SourceOrder actual) {
        assertSourceOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertSourceOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceOrderAllUpdatablePropertiesEquals(SourceOrder expected, SourceOrder actual) {
        assertSourceOrderUpdatableFieldsEquals(expected, actual);
        assertSourceOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceOrderAutoGeneratedPropertiesEquals(SourceOrder expected, SourceOrder actual) {
        assertThat(expected)
            .as("Verify SourceOrder auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceOrderUpdatableFieldsEquals(SourceOrder expected, SourceOrder actual) {
        assertThat(expected)
            .as("Verify SourceOrder relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceOrderUpdatableRelationshipsEquals(SourceOrder expected, SourceOrder actual) {
        // empty method
    }
}
